apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  bootstrap-servers: ${{ values.bootstrap-servers| dump }}
  topic: ${{ values.topic | dump}}
  group-id: ${{ values.group-id| dump }}
  sasl:
    mechanism: ${{ values.sasl.mechanism| dump }}
    username: ${{ values.sasl.username| dump }}
    password: ${{ values.sasl.password| dump }}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest